lee-kimmixq/expense-mgmt-app-frontend

- .eslintrc.js
- src/App.css
- src/App.js
- src/components/UI/atoms/AppTitle.jsx
- src/components/UI/atoms/AppTitleStandalone.jsx
- src/components/UI/atoms/InputField.jsx
- src/components/UI/atoms/PrimaryBtn.jsx
- src/components/UI/molecules/LoginForm.jsx
- src/components/pages/Login.jsx
- src/index.js
https://lee-kimmixq.atlassian.net/browse/MC-21
> MC-21 Created front-end component for login page

- src/App.css
- src/index.js
https://lee-kimmixq.atlassian.net/browse/MC-34
> MC-24 updated background to linear gradient

- src/App.js
- src/components/UI/atoms/PageHeader.jsx
- src/components/UI/atoms/PrimaryBtn.jsx
- src/components/UI/molecules/SignupForm.jsx
- src/components/pages/Signup.jsx
- src/index.js
https://lee-kimmixq.atlassian.net/browse/MC-32
> MC-32 create frontend components

- public/index.html
- src/App.css
- src/App.js
- src/components/UI/atoms/GenerateIcon.jsx
- src/components/UI/atoms/LinkTxt.jsx
- src/components/UI/atoms/ListTxnText.jsx
- src/components/UI/atoms/NavTab.jsx
- src/components/UI/atoms/PageHeader.jsx
- src/components/UI/atoms/TotalValuePrimary.jsx
- src/components/UI/molecules/CategoryAvatar.jsx
- src/components/UI/molecules/ExpIncNav.jsx
- src/components/UI/organisms/ListTxn.jsx
- src/components/pages/Dashboard.jsx
https://lee-kimmixq.atlassian.net/browse/MC-33
> Mc 33 - Set up frontend components for dashboard page

- public/index.html
https://lee-kimmixq.atlassian.net/browse/MC-54
> MC-54 added stylesheet to import poppins font

- src/components/UI/organisms/NavBar.jsx
- src/components/pages/Dashboard.jsx
https://lee-kimmixq.atlassian.net/browse/MC-57
> MC-57 added navbar components

- package-lock.json
- package.json
- src/App.js
- src/components/UI/atoms/CenteredPageHeader.jsx
- src/components/pages/Signup.jsx
https://lee-kimmixq.atlassian.net/browse/MC-55
> MC-55 Added react router

- src/App.css
- src/App.js
- src/components/UI/atoms/GenerateIconLarge.jsx
- src/components/UI/atoms/InputField.jsx
- src/components/UI/atoms/PrimaryBtn.jsx
- src/components/UI/atoms/TxnAmtField.jsx
- src/components/UI/molecules/AddTxnForm.jsx
- src/components/UI/molecules/UploadReceiptBtn.jsx
- src/components/pages/AddTxn.jsx
https://lee-kimmixq.atlassian.net/browse/MC-44
> MC-44 Set up frontend components for Add Txn Form

- src/components/UI/molecules/LoginForm.jsx
- src/components/UI/molecules/SignupForm.jsx
https://lee-kimmixq.atlassian.net/browse/MC-51
> MC-51 connected FE and BE for signup page

- src/components/UI/molecules/CategoryAvatar.jsx
- src/components/UI/molecules/ExpIncNav.jsx
- src/components/UI/molecules/LoginForm.jsx
- src/components/UI/organisms/ListTxn.jsx
- src/components/pages/Dashboard.jsx
- src/utils/fetcherGet.mjs
- src/utils/getMonthFirstLastDate.mjs
https://lee-kimmixq.atlassian.net/browse/MC-52
> MC-52 connected FE and BE for dashboard page

- src/App.js
- src/components/UI/atoms/InputField.jsx
- src/components/UI/atoms/TxnAmtField.jsx
- src/components/UI/molecules/AddTxnForm.jsx
- src/components/UI/molecules/CategoryAvatar.jsx
- src/components/UI/organisms/ListTxn.jsx
- src/components/UI/organisms/ListTxnByDate.jsx
- src/components/UI/organisms/NavBar.jsx
- src/components/pages/Dashboard.jsx
- src/components/pages/Transactions.jsx
- src/components/pages/TxnForm.jsx
- src/utils/fetcherPut.mjs
https://lee-kimmixq.atlassian.net/browse/MC-53
> MC-53 connected FE and BE for transactions

- src/components/UI/atoms/MonthPicker.jsx
- src/components/UI/molecules/TxnsNav.jsx
- src/components/pages/Dashboard.jsx
- src/components/pages/Transactions.jsx
- src/utils/getMonthFirstLastDate.mjs
https://lee-kimmixq.atlassian.net/browse/MC-66
> MC-66 made transactions page dynamic to selected month

- .gitignore
- package-lock.json
- package.json
- src/App.js
- src/authentication/AuthContext.js
- src/components/UI/molecules/AddTxnForm.jsx
- src/components/UI/molecules/LoginForm.jsx
- src/components/UI/molecules/SignupForm.jsx
- src/components/pages/Account.jsx
- src/components/pages/Dashboard.jsx
- src/components/pages/Transactions.jsx
- src/components/pages/TxnForm.jsx
- src/index.js
- src/utils/fetcher.mjs
- src/utils/fetcherDelete.mjs
- src/utils/fetcherGet.mjs
- src/utils/fetcherPost.mjs
- src/utils/fetcherPut.mjs
https://lee-kimmixq.atlassian.net/browse/MC-88
> MC-88 refactored fetchers and backend route names on FE

- src/App.js
- src/components/UI/molecules/CatReportsNav.jsx
- src/components/UI/molecules/ReportsNav.jsx
- src/components/UI/organisms/ListCategory.jsx
- src/components/pages/Breakdown.jsx
- src/components/pages/Reports.jsx
https://lee-kimmixq.atlassian.net/browse/MC-47
> MC-47 Set up frontend components for breakdown page

- src/components/UI/atoms/AlertDialog.jsx
- src/components/UI/molecules/DeleteAlertDialog.jsx
- src/components/pages/TxnForm.jsx
https://lee-kimmixq.atlassian.net/browse/MC-69
> MC-69 added delete dialog on txn form

- src/components/UI/molecules/CategoryAvatar.jsx
- src/components/UI/molecules/CategoryDropdown.jsx
- src/components/UI/organisms/AddTxnForm.jsx
- src/components/UI/organisms/ListTxn.jsx
- src/components/UI/organisms/ListTxnByDate.jsx
- src/components/pages/TxnForm.jsx
https://lee-kimmixq.atlassian.net/browse/MC-68
https://lee-kimmixq.atlassian.net/browse/MC-78
> MC-68 populated categories in add txn form dropdown and seeded category avatar

- src/components/UI/molecules/BreakdownChart.jsx
- src/components/UI/molecules/ReportsDonutChart.jsx
- src/components/pages/Breakdown.jsx
- src/components/pages/Reports.jsx
- src/utils/getDayFirstLastDate.mjs
- src/utils/getWeekFirstLastDate.mjs
https://lee-kimmixq.atlassian.net/browse/MC-105
> MC-105 created pie charts for reports and breakdown pages

- src/components/pages/Dashboard.jsx
https://lee-kimmixq.atlassian.net/browse/MC-110
> MC-110 edited dashboard query to get txns for whole month

- src/App.js
- src/authentication/PublicOnlyRoute.js
https://lee-kimmixq.atlassian.net/browse/MC-94
> MC-94 added redirect from login to dashboard if auth is true

- src/components/UI/molecules/CatReportsNav.jsx
- src/components/UI/molecules/ExpIncNav.jsx
- src/components/UI/molecules/ReportsNav.jsx
- src/components/pages/Breakdown.jsx
- src/components/pages/Dashboard.jsx
- src/components/pages/Reports.jsx
- src/components/pages/Transactions.jsx
- src/utils/useTxns.js
https://lee-kimmixq.atlassian.net/browse/MC-100
> MC-100 refactored hooks and useSWR

- src/components/UI/molecules/UploadReceiptBtn.jsx
- src/components/UI/organisms/AddTxnForm.jsx
- src/components/pages/TxnForm.jsx
- src/utils/fetcher.mjs
https://lee-kimmixq.atlassian.net/browse/MC-115
> MC-115 set up file upload in add txn form

- src/App.css
- src/App.js
- src/components/UI/atoms/GenerateIcon.jsx
- src/components/UI/atoms/LinearProgressBar.jsx
- src/components/UI/atoms/PrimaryBtn.jsx
- src/components/UI/molecules/BudgetCards.jsx
- src/components/UI/molecules/CategoryDropdown.jsx
- src/components/UI/molecules/DeleteAlertDialog.jsx
- src/components/UI/molecules/ListBudgets.jsx
- src/components/UI/organisms/FormDialog.jsx
- src/components/UI/organisms/ListTxnByDate.jsx
- src/components/pages/Budgets.jsx
- src/components/pages/Dashboard.jsx
- src/components/pages/Transactions.jsx
- src/index.css
- src/index.js
https://lee-kimmixq.atlassian.net/browse/MC-117
> MC-117 - create frontend components for budget

- src/components/UI/atoms/Expand.jsx
- src/components/UI/atoms/GenerateIcon.jsx
- src/components/UI/atoms/GenerateIconBtn.jsx
- src/components/UI/atoms/MinMaxInputs.jsx
- src/components/UI/molecules/CategoryAvatar.jsx
- src/components/UI/molecules/FilterDialog.jsx
- src/components/UI/molecules/ListBudgets.jsx
- src/components/UI/molecules/MultipleCategorySelectDropdown.jsx
- src/components/UI/molecules/SortFilterDialog.jsx
- src/components/UI/organisms/FormDialog.jsx
- src/components/pages/Transactions.jsx
https://lee-kimmixq.atlassian.net/browse/MC-103
> MC-103: Implement sort filter functions in transactions and breakdown page (Frontend)

- src/components/UI/atoms/GenerateIconBtn.jsx
- src/components/pages/Budgets.jsx
- src/components/pages/Transactions.jsx
https://lee-kimmixq.atlassian.net/browse/MC-123
> MC-123: set up front end components for search function on transactions page

- src/App.js
- src/components/UI/molecules/BudgetCards.jsx
- src/components/UI/molecules/ViewReceiptBtn.jsx
- src/components/pages/Confirmation.jsx
- src/components/pages/Transactions.jsx
https://lee-kimmixq.atlassian.net/browse/MC-129
> MC-129: Implement email verification - frontend

- src/components/pages/Confirmation.jsx
https://lee-kimmixq.atlassian.net/browse/MC-129
> MC-129 - resolving branch conflicts

- src/components/UI/molecules/ListBudgets.jsx
- src/components/pages/Budgets.jsx
https://lee-kimmixq.atlassian.net/browse/MC-121
> MC-121 connect retrieve and update requests for budgets

- src/components/pages/Transactions.jsx
https://lee-kimmixq.atlassian.net/browse/MC-124
> MC-124 added filter to filter txns based on search query

- src/components/UI/molecules/DeleteBudgetAlertDialog.jsx
- src/components/UI/molecules/ListBudgets.jsx
- src/components/UI/organisms/FormDialog.jsx
- src/components/UI/organisms/ThreeBtnFormDialog.jsx
- src/components/pages/Budgets.jsx
- src/utils/useBudgets.js
https://lee-kimmixq.atlassian.net/browse/MC-132
> MC-132 connect fe and be for budgets

- src/components/UI/atoms/AlertSnackbar.jsx
- src/components/UI/molecules/LoginForm.jsx
- src/components/UI/molecules/SignupForm.jsx
- src/components/pages/Confirmation.jsx
- src/components/pages/EditTxnForm.jsx
- src/components/pages/Home.jsx
- src/components/pages/Transactions.jsx
https://lee-kimmixq.atlassian.net/browse/MC-96
> MC-96: custom positioning of snackbar for login/signup/add pages

- src/components/UI/atoms/LinkTxt.jsx
- src/components/UI/atoms/TxnAmtField.jsx
- src/components/UI/organisms/ListCategory.jsx
- src/components/UI/organisms/TxnForm.jsx
- src/components/pages/Dashboard.jsx
- src/components/pages/NewTxnForm.jsx
https://lee-kimmixq.atlassian.net/browse/MC-83
> MC-83: Update amount field in txn form to clear values on click

- src/components/UI/molecules/SortFilterDialog.jsx
- src/components/UI/organisms/ListCategory.jsx
- src/components/pages/Breakdown.jsx
- src/components/pages/Reports.jsx
- src/components/pages/Transactions.jsx
https://lee-kimmixq.atlassian.net/browse/MC-106
> MC-106 add links to reports that direct to filtered transaction page

- src/components/pages/Reports.jsx
https://lee-kimmixq.atlassian.net/browse/MC-142
> MC-142 fixed pie charts to be always month view

- public/index.html
- src/components/UI/atoms/PrimaryBtn.jsx
- src/components/UI/molecules/CategoryDropdown.jsx
- src/components/UI/molecules/LoginForm.jsx
- src/components/UI/molecules/SignupForm.jsx
- src/components/UI/organisms/TxnForm.jsx
https://lee-kimmixq.atlassian.net/browse/MC-97
> MC-97: Accept keyboard commands when filling forms

- src/components/UI/atoms/TxnAmtField.jsx
- src/components/UI/molecules/CategoryDropdown.jsx
- src/components/UI/molecules/LoginForm.jsx
- src/components/UI/organisms/TxnForm.jsx
https://lee-kimmixq.atlassian.net/browse/MC-145
> MC-145: Add form validation to txn form

- src/App.test.js
- src/components/UI/atoms/AccountNavTabs.jsx
- src/components/UI/atoms/AccountProfileHeader.jsx
- src/components/UI/atoms/GenerateIcon.jsx
- src/components/UI/atoms/GenerateIconBtn.jsx
- src/components/UI/atoms/GenerateIconLarge.jsx
- src/components/UI/atoms/InputField.jsx
- src/components/UI/atoms/LinearProgressBar.jsx
- src/components/UI/atoms/LinkTxt.jsx
- src/components/UI/atoms/ListTxnText.jsx
- src/components/UI/atoms/NavTab.jsx
- src/components/UI/atoms/PrimaryBtn.jsx
- src/components/UI/atoms/TxnAmtField.jsx
- src/components/UI/molecules/BudgetCards.jsx
- src/components/UI/molecules/CatReportsNav.jsx
- src/components/UI/molecules/ExpIncNav.jsx
- src/components/UI/molecules/ListBudgets.jsx
- src/components/UI/molecules/ReportsNav.jsx
- src/components/UI/molecules/UploadReceiptBtn.jsx
- src/components/UI/molecules/ViewReceiptBtn.jsx
- src/components/UI/organisms/ListTxnByDate.jsx
- src/components/pages/Budgets.jsx
- src/components/pages/Reports.jsx
- src/components/pages/Transactions.jsx
- src/index.js
- src/utils/theme.js
https://lee-kimmixq.atlassian.net/browse/MC-147
> MC-147: Improve bundling size on frontend

- src/components/UI/atoms/AppTitle.jsx
- src/components/UI/atoms/GenerateIconLarge.jsx
- src/components/UI/atoms/InputField.jsx
- src/components/UI/atoms/OneBtnAlertDialog.jsx
- src/components/UI/molecules/LoginForm.jsx
- src/components/UI/molecules/SignupForm.jsx
- src/components/UI/organisms/SignupSuccessDialog.jsx
- src/components/pages/EditTxnForm.jsx
- src/components/pages/Home.jsx
- src/components/pages/NewTxnForm.jsx
https://lee-kimmixq.atlassian.net/browse/MC-137
> MC-137: Updated UX flow for sign up to show dialog instead of redirecting to login with success snackbar

- src/components/pages/Reports.jsx
https://lee-kimmixq.atlassian.net/browse/MC-139
> MC-139 edit reports bar chart so that columns with 0 value also appear

- src/components/pages/Transactions.jsx
https://lee-kimmixq.atlassian.net/browse/MC-144
> MC-144 fixed snackbars showing on rerender on txn page

- src/components/UI/molecules/CategoryDropdown.jsx
- src/components/UI/molecules/MultipleCategorySelectDropdown.jsx
- src/components/pages/Account.jsx
- src/utils/useUsers.js
https://lee-kimmixq.atlassian.net/browse/MC-155
> MC-155 make user name on account page dynamic

- src/components/pages/Breakdown.jsx
https://lee-kimmixq.atlassian.net/browse/MC-153
> MC-153 fix donut chart size on first render in breakdown

- src/components/pages/Breakdown.jsx
https://lee-kimmixq.atlassian.net/browse/MC-154
> MC-154 fix breakdown page bottom covered by nav bar

- src/components/UI/molecules/TxnsNav.jsx
- src/components/pages/Transactions.jsx
https://lee-kimmixq.atlassian.net/browse/MC-151
> MC-151 updated txndatemin and txndatemax filters on month change
